#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use PronouncePHP\Transcribe\Transcriber;
use PronouncePHP\Build\Builder;
use PronouncePHP\LookupCommand;

require 'vendor/autoload.php';

$app = new Application('Pronounce-PHP', '0.4');

$transcriber = new Transcriber();
$builder = new Builder();

$app->add(new LookupCommand($transcriber, $builder));

$app->run();