#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use PronouncePHP\Transcribe\Transcriber;
use PronouncePHP\Hyphenate\Hyphenator;
use PronouncePHP\Build\Builder;
use PronouncePHP\LookupCommand;
use PronouncePHP\HyphenateCommand;

require 'vendor/autoload.php';

$GLOBALS['status'] = 0;

$app = new Application('Pronounce-PHP', '0.6');

$transcriber = new Transcriber();
$hyphenator = new Hyphenator();
$builder = new Builder();

$app->add(new LookupCommand($transcriber, $hyphenator, $builder));
$app->add(new HyphenateCommand($hyphenator, $builder));

$app->run();