#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use PronouncePHP\Config\Startup;
use PronouncePHP\Transcribe\Transcriber;
use PronouncePHP\Hyphenate\Hyphenator;
use PronouncePHP\Build\Builder;
use PronouncePHP\AllCommand;
use PronouncePHP\HyphenateCommand;
use PronouncePHP\LookupCommand;

require 'vendor/autoload.php';

$GLOBALS['status'] = 0;

$app = new Application('Pronounce-PHP', '0.8');

$startup = new Startup();
$startup->configure();

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$transcriber = new Transcriber();
$hyphenator = new Hyphenator();
$builder = new Builder();

$app->add(new AllCommand($transcriber, $hyphenator, $builder));
$app->add(new HyphenateCommand($hyphenator, $builder));
$app->add(new LookupCommand($transcriber, $hyphenator, $builder));

$app->run();