#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use PronouncePHP\PhoneticCodes\Arpabet;
use PronouncePHP\PhoneticCodes\Ipa;
use PronouncePHP\PhoneticCodes\Spelling;
use PronouncePHP\WordCommand;

require 'vendor/autoload.php';

$app = new Application('Pronounce-PHP', '0.1');

$arpabet = new Arpabet();
$ipa = new Ipa();
$spelling = new Spelling();

$app->add(new WordCommand($arpabet, $ipa, $spelling));

$app->run();